### ISSUE TITLE
Need updates to Readme for instructions to step 4 patching-stackset.yaml instructions

### ISSUE THREAD

**Issue by 0x-gaurav** [aws-samples/self-service-patching-solution-for-multi-account-organisation#1]
need to update instructions for stackset.yaml those options are no longer available in cloudformation stackset, also getting an error for IAM role not having permissions, i am guessing its because of the change in stackset templates as we no longer have options to deploy to OU

**Comment by pursachi** [comment]
I am able to deploy the stackset by following the instructions, please check if you have completed the prerequisite properly. 
I can also see the deploy to OU option in the stackset deployment.
